apiVersion: apps/v1
kind: Deployment
metadata:
  name: duo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: duo
  template:
    metadata:
      labels:
        app: duo
    spec:
      containers:
      - name: duo
        image: vaishnavi2211/duo:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_IP
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: mongo-url
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-user
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password

        - name : REDIS_IP
          valueFrom:
            configMapKeyRef:
              name: redis-config
              key: redis-url
        - name : REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: redis-config
              key: redis-port
        - name : SESSION_SECRET
          value : "secret"
              


---
apiVersion: v1
kind: Service
metadata:
  name: duo
spec:
  type: LoadBalancer
  selector:
    app: duo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: duo-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: duo
            port:
              number: 80


