version: "3"
services:
  nginx:
    ports:
      - "3000:80"
    restart: always
  duo:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    # environment:
    #   - NODE_ENV=development
    #   - MONGO_USER=vaishnavi
    #   - MONGO_PASSWORD=mypassword
    #   - SESSION_SECRET=secret
    env_file:
      - .env

    command: npm run dev
  mongo:
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=vaishnavi
    #   - MONGO_INITDB_ROOT_PASSWORD=mypassword
    env_file:
      - .env
