version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  duo:
    build: .
    image: vaishnavi2211/duo
    environment:
      - PORT=3000
    depends_on:
      - mongo

  mongo:
    image: mongo
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=vaishnavi
    #   - MONGO_INITDB_ROOT_PASSWORD=mypassword
    env_file:
      - .env
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis

volumes:
  mongo-db:
